# Generated by Django 5.2.17 on 2026-09-24 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Actualizado en')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='Eliminado en')),
                ('fecha', models.DateField()),
                ('tipo_registro', models.CharField(max_length=50)),
                ('descripcion_accion', models.TextField(blank=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='accounts.funcionario')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='configuration.item')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['-fecha'],
            },
        ),
    ]
