# Generated by Django 5.2.17 on 2026-09-30 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Actualizado en')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='Eliminado en')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('record_type', models.CharField(max_length=50, verbose_name='Tipo de registro')),
                ('action_description', models.TextField(blank=True, verbose_name='Descripción de la acción')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='configuration.item', verbose_name='Ítem')),
                ('official', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='accounts.official', verbose_name='Funcionario')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['-date'],
            },
        ),
    ]
